### PR TITLE
Add simple deploy script to travis config

### PR DESCRIPTION
**Pull request by timrourke**
This PR adds a simple Travis deploy script. We can figure out how to determine where to push our specific deploys later - for now I will add the env vars and hardcode it to always push to `footprints-1`.

### CODE REVIEW

**Comment by bartboy011** [comment]
Wow, I completely missed this PR and wrote my own version of it.

**Comment by bartboy011** [comment]
The thing that was missing here was the pem file to give SSH access to Travis. I solved that by encrypting a pem key, adding the encryption key as an encrypted env var to Travis, then including a step to decrypt that file during a successful master branch build, right before running the cap commands

**Comment by timrourke** [comment]
@bartboy011 yep i didn't request review for this yet, added those changes

**Comment by timrourke** [comment]
i'll close this since it looks like we did identical work here.

**Pull request closed without merging**
